set_property IOSTANDARD LVCMOS25 [get_ports resetn]
set_property IOSTANDARD LVCMOS33 [get_ports clk_ddmtd_locked]
set_property IOSTANDARD LVCMOS33 [get_ports {board_clk[0]}]
set_property PACKAGE_PIN F22 [get_ports resetn]
set_property PACKAGE_PIN T22 [get_ports clk_ddmtd_locked]
set_property PACKAGE_PIN Y9 [get_ports {board_clk[0]}]
create_clock -period 10.000 -name board_clk [get_ports board_clk]
